//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public int Id { get; set; }
        public string LicensePlate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string ChassisNo { get; set; }
        public string CustomerName { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> MechanicId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public bool BookingStatus { get; set; }
        public Nullable<System.DateTime> BookingConfirmDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Dealers Dealers { get; set; }
        public virtual Mechanics Mechanics { get; set; }
        public virtual Services Services { get; set; }
    }
}
